### ISSUE TITLE
Documentation Error for mesh.uniform.refinement.count

### ISSUE THREAD

**Issue by xivps** [OpenParEM/OpenParEM2D#3]
**Describe the bug**
The documentation pdf does list the `mesh.uniform.refinement.count` parameter, however the actual string ist `mesh.uniform_refinement.count`, with an underscore instead of a dot

The software does complain about a wrong entry in the project file when using the dot string.

**Comment by M8kmyday** [comment]
I just saw this.  I'm still learning GitHub, and I thought I would get a notice when an issue was opened, but that didn't happen.

Thanks for the alert on the documentation error.  I'll go ahead and fix that.
